flowerShop/Ictshop/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ictshop.Models;
using PagedList;

namespace Ictshop.Areas.Admin.Controllers
{
    public class HomeController : Controller
        
    {
        Qlbanhang db = new Qlbanhang();
       
        // GET: Admin/Home
        
        public ActionResult Index(int ?page)
        {
            
            // 1. Tham số int? dùng để thể hiện null và kiểu int( số nguyên)
            // page có thể có giá trị là null ( rỗng) và kiểu int.

            // 2. Nếu page = null thì đặt lại là 1.
            if (page == null) page = 1;

            // 3. Tạo truy vấn sql, lưu ý phải sắp xếp theo trường nào đó, ví dụ OrderBy
            // theo Masp mới có thể phân trang.
            var sp = db.Sanphams.OrderByDescending(x => x.Masp);

            // 4. Tạo kích thước trang (pageSize) hay là số sản phẩm hiển thị trên 1 trang
            int pageSize = 5;

            // 4.1 Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
            int pageNumber = (page ?? 1);

            // 5. Trả về các sản phẩm được phân trang theo kích thước và số trang.
            return View(sp.ToPagedList(pageNumber, pageSize));

        }

        // Xem chi tiết người dùng GET: Admin/Home/Details/5 
        public ActionResult Details(int id)
        {
            var dt = db.Sanphams.Find(id);
            return View(dt);
        }

        // Tạo sản phẩm mới phương thức GET: Admin/Home/Create
        public ActionResult Create()
        {
            ViewBag.Mahang = new SelectList(db.Hangsanxuats, "Mahang", "Tenhang");
            ViewBag.Mahdh = new SelectList(db.Hedieuhanhs, "Mahdh", "Tenhdh");
            return View();
        }

        // POST: Admin/Sanphams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Masp,Tensp,Giatien,Soluong,Mota,Thesim,Bonhotrong,Sanphammoi,Ram,Anhbia,Mahang,Mahdh")] Sanpham sanpham)
        {
            if (ModelState.IsValid)
            {
                db.Sanphams.Add(sanpham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Mahang = new SelectList(db.Hangsanxuats, "Mahang", "Tenhang", sanpham.Mahang);
            ViewBag.Mahdh = new SelectList(db.Hedieuhanhs, "Mahdh", "Tenhdh", sanpham.Mahdh);
            return View(sanpham);
        }


        // Sửa sản phẩm GET lấy ra ID sản phẩm: Admin/Home/Edit/5
        public ActionResult Edit(int id)
        {
            // Hiển thị dropdownlist
            var dt = db.Sanphams.Find(id);
            var hangselected = new SelectList(db.Hangsanxuats, "Mahang", "Tenhang",dt.Mahang);
            ViewBag.Mahang = hangselected;
            var hdhselected = new SelectList(db.Hedieuhanhs, "Mahdh", "Tenhdh",dt.Mahdh);
            ViewBag.Mahdh = hdhselected;
           // 
            return View(dt);
        }

        // POST: Admin/Home/Edit/5
        [HttpPost]
        public ActionResult Edit(Sanpham sanpham)
        {
            try
            {
                // Sửa sản phẩm theo mã sản phẩm
                var oldItem = db.Sanphams.Find(sanpham.Masp);
                oldItem.Tensp = sanpham.Tensp;
                oldItem.Giatien = sanpham.Giatien;
                oldItem.Soluong = sanpham.Soluong;
                oldItem.Mota = sanpham.Mota;
                oldItem.Anhbia = sanpham.Anhbia;
                oldItem.Mahang = sanpham.Mahang;
                oldItem.Mahdh = sanpham.Mahdh;
                // lưu lại
                db.SaveChanges();
                // xong chuyển qua index
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        
        // Xoá sản phẩm phương thức GET: Admin/Home/Delete/5
        public ActionResult Delete(int id)
        {
            var dt = db.Sanphams.Find(id);
            return View(dt);
        }

        // Xoá sản phẩm phương thức POST: Admin/Home/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                //Lấy được thông tin sản phẩm theo ID(mã sản phẩm)
                var dt = db.Sanphams.Find(id);
                // Xoá
                db.Sanphams.Remove(dt);
                // Lưu lại
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

flowerShop/Ictshop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ictshop.Controllers
{
    public class HomeController : Controller
    {
      
        public ActionResult Index()
        {
       
            return View();

        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult SlidePartial()
        {
            return PartialView();

        }
    }
}

flowerShop/Ictshop/Controllers/SanphamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ictshop.Models;

namespace Ictshop.Controllers
{
    public class SanphamController : Controller
    {
        Qlbanhang db = new Qlbanhang();
        public ActionResult Index(string searchString)
        {
            var links = from l in db.Sanphams
                        select l;

            if (!String.IsNullOrEmpty(searchString))
            {
                links = links.Where(s => s.Tensp.Contains(searchString));
            }

            return PartialView(links);
        }

        // GET: Sanpham
        public ActionResult womenday()
        {
            var ip = db.Sanphams.Where(n=>n.Mahang==2).Take(4).ToList();
           return PartialView(ip);
        }
        public ActionResult motherday()
        {
            var ss = db.Sanphams.Where(n => n.Mahang == 1).Take(4).ToList();
            return PartialView(ss);
        }
        public ActionResult valentine()
        {
            var mi = db.Sanphams.Where(n => n.Mahang == 3).Take(4).ToList();
            return PartialView(mi);
        }

        public ActionResult listproducts()
        {
            var list = db.Sanphams.ToList();
                
            return PartialView(list);
        }

        public ActionResult searchByName(string name)
        {
            var list = db.Sanphams.Where(n=>n.Tensp.Contains(name));
            return PartialView(list);
        }
   

        //public ActionResult dttheohang()
        //{
        //    var mi = db.Sanphams.Where(n => n.Mahang == 5).Take(4).ToList();
        //    return PartialView(mi);
        //}
        public ActionResult xemchitiet(int Masp=0)
        {
            var chitiet = db.Sanphams.SingleOrDefault(n=>n.Masp==Masp);
            if (chitiet == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(chitiet);
        }

    }

}

flowerShop/Ictshop/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/layout.cshtml";
}


<div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="section-title text-center position-relative pb-3 mb-5 mx-auto" style="max-width: 600px;">
            <h3 class="fw-bold text-primary text-uppercase">About Us</h3>
            <h1 class="mb-0">“Make Important Days Perfect – Make Ordinary Days Memorables"</h1>
        </div>

    </div>
    <div class="row g-0 mb-3">
        <div class="col-sm-6 wow zoomIn" data-wow-delay="0.2s">
            <h5 class="mb-3" style=" text-align: center"><i class="fa fa-check text-primary me-3"></i> We have flowers arangement artists.</h5>
            <h5 class="mb-3" style=" text-align: center"><i class="fa fa-check text-primary me-3"></i> We are one the largest florists today.</h5>
        </div>
        <div class="col-sm-6 wow zoomIn" data-wow-delay="0.2s">

            <h5 class="mb-3" style=" text-align: center"><i class="fa fa-check text-primary me-3"></i>We shop ofers to  you all kinds of flowers:  fresh , wax,paper...</h5>
            <h5 class="mb-3" style=" text-align: center"><i class="fa fa-check text-primary me-3"></i>We want to bring people to understand the beauty of flowers.</h5>
        </div>
    </div>
</div>


<div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="section-title text-center position-relative pb-3 mb-5 mx-auto" style="max-width: 600px;">
            <h3 class="fw-bold text-primary text-uppercase"> Founder</h3>
            <h1 class="mb-0">“The material we make the main product is fresh flowers"</h1>
        </div>
        <div class="col-md-4">
            <img src="~/HinhanhSP/team-1.jpg" class="img-responsive" alt="" />
            <h2 style=" text-align: center" >Mr.John</h2>
            <h4>
                Manager - the person who works and gives credit to the members
            </h4>


        </div>
        <div class="col-md-4">
            <img src="~/HinhanhSP/team-2.jpg" class="img-responsive" alt="" />
            <h2 style=" text-align: center" >Mrs.Linda</h2>
            <h4>
                Photo sample - art expert, flower arrangement artist
            </h4>

        </div>
        <div class="col-md-4">
            <img src="~/HinhanhSP/team-3.jpg" S class="img-responsive" alt="" />
            <h2 style=" text-align: center">Mr.Alex</h2>
            <h4>
                Photographer - take pictures of samples and find customers
            </h4>

        </div>
    </div>
</div>

flowerShop/Ictshop/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/layout.cshtml";

}
<div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="section-title text-center position-relative pb-3 mb-5 mx-auto" style="max-width: 600px;">
            <h5 class="fw-bold text-primary text-uppercase">Contact Us</h5>
            <h1 class="mb-0">If You Have Any Query, Feel Free To Contact Us</h1>
        </div>
        <div class="row g-5 mb-5">
            <div class="col-lg-4">
                <div class="d-flex align-items-center wow fadeIn" data-wow-delay="0.1s">
                    <div class="bg-primary d-flex align-items-center justify-content-center rounded" style="width: 60px; height: 60px;">
                        <i class="bi bi-telephone text-white"></i>
                    </div>
                    <div class="ps-4">
                        <h5 class="mb-2">Call to ask any question</h5>
                        <h4 class="text-primary mb-0">+012 345 6789</h4>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="d-flex align-items-center wow fadeIn" data-wow-delay="0.4s">
                    <div class="bg-primary d-flex align-items-center justify-content-center rounded" style="width: 60px; height: 60px;">
                        <i class="fa fa-envelope-open text-white"></i>
                    </div>
                    <div class="ps-4">
                        <h5 class="mb-2">Email to get free quote</h5>
                        <h4 class="text-primary mb-0">info@example.com</h4>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="d-flex align-items-center wow fadeIn" data-wow-delay="0.8s">
                    <div class="bg-primary d-flex align-items-center justify-content-center rounded" style="width: 60px; height: 60px;">
                        <i class="bi bi-geo-alt  text-white"></i>
                    </div>
                    <div class="ps-4">
                        <h5 class="mb-2">Visit our office</h5>
                        <h4 class="text-primary mb-0">So 8, Ton That Thuyet, Ha Noi</h4>
                    </div>
                </div>
            </div>
        </div>
        <div class="row g-5">
            <div class="col-lg-6 wow slideInUp" data-wow-delay="0.3s">
                <form>
                    <div class="row g-3">
                        <div class="col-md-6">
                            <input type="text" class="form-control border-0 bg-light px-4" placeholder="Your Name" style="height: 55px;">
                        </div>
                        <div class="col-md-6">
                            <input type="email" class="form-control border-0 bg-light px-4" placeholder="Your Email" style="height: 55px;">
                        </div>
                       
                        <div class="col-12">
                            <textarea class="form-control border-0 bg-light px-4 py-3" rows="4" placeholder="Message"></textarea>
                        </div>
                        <div class="col-12">
                            <button class="btn btn-primary w-100 py-3" type="submit">Send Message</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-6 wow slideInUp" data-wow-delay="0.6s">
                <iframe class="position-relative rounded w-100 h-100"
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
                        frameborder="0" style="min-height: 350px; border:0;" allowfullscreen="" aria-hidden="false"
                        tabindex="0"></iframe>
            </div>
        </div>
    </div>
</div>

flowerShop/Ictshop/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Flowershop ";

}


<br />

<div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="section-title text-center position-relative pb-3 mb-5 mx-auto" style="max-width: 600px;">
            <h3 class="fw-bold text-primary text-uppercase">About Us</h3>
            <h1 class="mb-0">“Make Important Days Perfect – Make Ordinary Days Memorables"</h1>
        </div>

    </div>
    <div class="row g-0 mb-3">
        <div class="col-sm-6 wow zoomIn" data-wow-delay="0.2s">
            <h5 class="mb-3" style=" text-align: center"><i class="fa fa-check text-primary me-3"></i> We have flowers arangement artists.</h5>
            <h5 class="mb-3" style=" text-align: center"><i class="fa fa-check text-primary me-3"></i> We are one the largest florists today.</h5>
        </div>
        <div class="col-sm-6 wow zoomIn" data-wow-delay="0.2s">

            <h5 class="mb-3" style=" text-align: center"><i class="fa fa-check text-primary me-3"></i>We shop ofers to  you all kinds of flowers:  fresh , wax,paper...</h5>
            <h5 class="mb-3" style=" text-align: center"><i class="fa fa-check text-primary me-3"></i>We want to bring people to understand the beauty of flowers.</h5>
        </div>
    </div>
</div>

<br />
<br />
<div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="section-title text-center position-relative pb-3 mb-5 mx-auto" style="max-width: 600px;">
            <h3 class="fw-bold text-primary text-uppercase">Ingredient</h3>
            <h1 class="mb-0">“The material we make the main product is fresh flowers"</h1>
        </div>

    </div>
    <div class="col-md-4">
        <img src="~/HinhanhSP/nl1.jpg" class="img-responsive" alt="" />
     
        <br />

        <h3 style=" text-align: center">Chrysanthemum Field</h3>
        <h5>
            Need regular watering, especially from the time the plant begins to take root until flowers.
            
        </h5>


    </div>
    <div class="col-md-4">
        <img src="~/HinhanhSP/nl2.jpg" class="img-responsive" alt="" />
        
        <br />
        <h3 style=" text-align: center">Sunflower Field</h3>
        <h5>
            Need regular watering, especially from the time the plant begins to take root until flowers.
        </h5>

    </div>
    <div class="col-md-4">
        <img src="~/HinhanhSP/nl3.jpg" class="img-responsive" alt="" />
        
        <br />
        <h3 style=" text-align: center">Rose Field</h3>

        <h5>
            Need regular watering, especially from the time the plant begins to take root until flowers.
            
        </h5>

    </div>
</div>
<br />
<br />

<div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="section-title text-center position-relative pb-3 mb-5 mx-auto" style="max-width: 600px;">
            <h3 class="fw-bold text-primary text-uppercase">Best Saller</h3>
        </div>

        <div class="dt">
            @Html.Action("valentine", "Sanpham")
        </div>
        <br />
        <br />
        <div class="dt">

            @Html.Action("motherday", "Sanpham")
        </div>

    </div>
</div>

<br />

flowerShop/Ictshop/Views/Home/SlidePartial.cshtml
<img class="img-responsive" src="~/HinhanhSP/banner3.jpg" />